{% set version = "1.1.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bglr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/BGLR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/BGLR/BGLR_{{ version }}.tar.gz
  sha256: 97c5bb8a461eb408e907693811b2d917efc993000da06591a83a3f5529451ea7

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
    - r-truncnorm
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-mass
    - r-truncnorm

test:
  commands:
    - $R -e "library('BGLR')"           # [not win]
    - "\"%R%\" -e \"library('BGLR')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=BGLR
  license: GPL-3.0-only
  summary: Bayesian Generalized Linear Regression.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: BGLR
# Version: 1.0.8
# Date: 2018-11-24
# Title: Bayesian Generalized Linear Regression
# Author: Gustavo de los Campos, Paulino Perez Rodriguez,
# Maintainer: Paulino Perez Rodriguez <perpdgo@colpos.mx>
# Depends: R (>= 3.5.0)
# Imports: truncnorm
# Description: Bayesian Generalized Linear Regression.
# LazyLoad: true
# License: GPL-3
# NeedsCompilation: yes
# Packaged: 2018-11-07 04:39:20 UTC; pperez
# Repository: CRAN
# Date/Publication: 2018-11-11 07:20:03 UTC
