appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: r7gr7DblwvQj/qLauaYr9K/xK4bs/3oKkzxocQBib9WCpyP362oNNRJdD/0c3FuwqN5BQxdyal5OZ6KkJxRJ7fixqefZfkOgiJAEyAUPQKdYfFoBrWd5bdObggCXtOn9h/IjGcC3Q3eCnM33CnhO/OJyjJO+E80bC73OmYlWGCiJBnS68c9D4i+/a+Xzi0O+Z4CVLqbiMAacOX/WhS+vDjM5x8H3EQ64TNbOk930El0iQIkhGPNL2PJGBtrevpSRZdwLkKISlOzSzRc2hHQge/FEquJdGMkD3uPAtt0FmveNIMUy3J32rfuPPNlikl9vAwQkLQ0Z2htCBOrfETAzSr6SCmZCKU+cmSdRMKQelaV7jX8yfnc35oDbMetVZmnQVlofpY32fQLqx9m/DkrSrPSuc7m2LMYvigEm7EKCZo61nugd/2pzlAi/ybn5Wazj2NkaLdBqdXOXmkUcB49NWkpTEdobeI+6Wu/A9IicJ3rNFi2zAXzoFa2BWA1TYZ9o8bBi82l+olWVbmvC8JKxl01Pme2sQOZDMdrMITcwfVxLzTV/tvDEM7RWFBl44/2OsXtx7X6N8krUsA4pfdcZeeSMWaxX+qpv9B8CRp4GlV4deHUEBhqPg49KrE2gcN7iKWT3oEMPCcoW1tl1LEO412oQ9TIV8CIAxOKA0RuKIpU=}
bot:
  automerge: true
